name: "Build Appliction (Nuitka)"

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows-latest
            flags: >-
              --windows-console-mode=disable
              --windows-icon-from-ico=assets/icons/cleansheet_logo.ico
            artifact_name: CleanSheet-Windows
            output_name: CleanSheet.exe

          - os: ubuntu-latest
            flags: >-
              --linux-app-icon=assets/icons/cleansheet_logo.png
            artifact_name: CleanSheet-Linux
            output_name: CleanSheet

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: "3.12"

      - name: Install Linux build dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y patchelf

      - name: Install uv
        uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d

      - name: Install Dependencies
        run: uv sync --locked

      - name: Compile Application
        shell: bash
        run: |
          uv run python -m nuitka \
            --onefile \
            --enable-plugin=tk-inter \
            --include-data-dir=assets=assets \
            --assume-yes-for-downloads \
            --output-filename="${{ matrix.output_name }}" \
            ${{ matrix.flags }} \
            src/cleansheet/main.py

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: ${{ matrix.output_name }}
